//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:2.0.50727.9151
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PVI_7b.Models
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contact", Namespace="http://schemas.datacontract.org/2004/07/PVI_7b.Models")]
    public partial class Contact : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string IdField;
        
        private string LastnameField;
        
        private string PhoneNumberField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lastname
        {
            get
            {
                return this.LastnameField;
            }
            set
            {
                this.LastnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber
        {
            get
            {
                return this.PhoneNumberField;
            }
            set
            {
                this.PhoneNumberField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ISomeWcfService")]
public interface ISomeWcfService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISomeWcfService/HelloWorld", ReplyAction="http://tempuri.org/ISomeWcfService/HelloWorldResponse")]
    string HelloWorld();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISomeWcfService/GetDict", ReplyAction="http://tempuri.org/ISomeWcfService/GetDictResponse")]
    PVI_7b.Models.Contact[] GetDict();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISomeWcfService/AddDict", ReplyAction="http://tempuri.org/ISomeWcfService/AddDictResponse")]
    PVI_7b.Models.Contact AddDict(PVI_7b.Models.Contact contact);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISomeWcfService/PutDict", ReplyAction="http://tempuri.org/ISomeWcfService/PutDictResponse")]
    PVI_7b.Models.Contact PutDict(PVI_7b.Models.Contact contact);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISomeWcfService/DeleteDict", ReplyAction="http://tempuri.org/ISomeWcfService/DeleteDictResponse")]
    PVI_7b.Models.Contact DeleteDict(PVI_7b.Models.Contact contact);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface ISomeWcfServiceChannel : ISomeWcfService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class SomeWcfServiceClient : System.ServiceModel.ClientBase<ISomeWcfService>, ISomeWcfService
{
    
    public SomeWcfServiceClient()
    {
    }
    
    public SomeWcfServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public SomeWcfServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public SomeWcfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public SomeWcfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string HelloWorld()
    {
        return base.Channel.HelloWorld();
    }
    
    public PVI_7b.Models.Contact[] GetDict()
    {
        return base.Channel.GetDict();
    }
    
    public PVI_7b.Models.Contact AddDict(PVI_7b.Models.Contact contact)
    {
        return base.Channel.AddDict(contact);
    }
    
    public PVI_7b.Models.Contact PutDict(PVI_7b.Models.Contact contact)
    {
        return base.Channel.PutDict(contact);
    }
    
    public PVI_7b.Models.Contact DeleteDict(PVI_7b.Models.Contact contact)
    {
        return base.Channel.DeleteDict(contact);
    }
}
